services:
  init-volume:
    image: busybox
    command: chown -R 1000:1000 /app/data /app/logs
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

  app:
    image: ghcr.io/shan-hee/cloudpaste-x:latest  # 请替换为您的GitHub用户名
    container_name: cloudpaste-app
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_PATH=/app/data/db.sqlite
      - LOG_FILE_PATH=/app/logs/app.log
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=${MINIO_ROOT_USER:-minioadmin}
      - S3_SECRET_KEY=${MINIO_ROOT_PASSWORD:-minioadmin}
      - S3_BUCKET=${S3_BUCKET:-cloudpaste}
      - S3_REGION=${S3_REGION:-us-east-1}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
      - S3_AUTO_CREATE_BUCKET=${S3_AUTO_CREATE_BUCKET:-true}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-5}
      - TOTAL_STORAGE_GB=${TOTAL_STORAGE_GB:-10}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - PUBLIC_URL=http://${HOST:-0.0.0.0}:${PORT:-3000}
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - minio
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  minio:
    image: minio/minio
    container_name: cloudpaste-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
      - MINIO_BROWSER=${MINIO_BROWSER:-on}
      - MINIO_DOMAIN=${MINIO_DOMAIN:-minio}
      - MINIO_REGION=${MINIO_REGION:-us-east-1}
    volumes:
      - ./minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    name: cloudpaste-network
    driver: bridge 