version: '3.8'

services:
  init-volume:
    image: busybox
    command: chown -R 1000:1000 /app/data /app/logs
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

  app:
    image: ghcr.io/${GITHUB_USERNAME}/cloudpaste-x:latest
    container_name: cloudpaste-app
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_PATH=/app/data/db.sqlite
      - LOG_FILE_PATH=/app/logs/app.log
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=${MINIO_ROOT_USER:-minioadmin}
      - S3_SECRET_KEY=${MINIO_ROOT_PASSWORD:-minioadmin}
      - S3_BUCKET=${S3_BUCKET:-cloudpaste}
      - S3_REGION=${S3_REGION:-us-east-1}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-5}
      - TOTAL_STORAGE_GB=${TOTAL_STORAGE_GB:-10}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - PUBLIC_URL=http://${HOST:-localhost}:${PORT:-3000}
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
      - ENABLE_REQUEST_LOGGING=${ENABLE_REQUEST_LOGGING:-true}
      - ENABLE_RESPONSE_CACHE=${ENABLE_RESPONSE_CACHE:-true}
      - CACHE_DURATION=${CACHE_DURATION:-3600}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      init-volume:
        condition: service_completed_successfully
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  minio:
    image: minio/minio
    container_name: cloudpaste-minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    name: cloudpaste-network
    driver: bridge 